const redModules = [
  {
    key: "network_infrastructure_recon",
    title: "Network & Infrastructure Recon",
    description: "Host and network discovery with service-level reconnaissance.",
    targetLabel: "Target (IP/domain/CIDR)",
    targetPlaceholder: "8.8.8.8 or example.com or 192.168.1.0/24",
    auxLabel: "Optional Context",
    auxPlaceholder: "Port range, scan strategy, or notes",
    capabilities: [
      "IP Lookup (GeoIP, ASN, ISP)",
      "Reverse IP Lookup",
      "CIDR Expansion & Range Scanning",
      "Port Scanning (TCP/UDP, service detection)",
      "Banner Grabbing",
      "Service Fingerprinting",
      "Traceroute Mapping",
      "IPv6 Recon",
    ],
  },
  {
    key: "domain_dns_intelligence",
    title: "Domain & DNS Intelligence",
    description: "Comprehensive DNS and domain intelligence collection.",
    targetLabel: "Domain",
    targetPlaceholder: "example.com",
    auxLabel: "Optional Wordlist/Permutation Seed",
    auxPlaceholder: "api,dev,staging",
    capabilities: [
      "WHOIS Lookup",
      "DNS Records (A, AAAA, MX, TXT, NS, CNAME, SOA)",
      "Subdomain Enumeration",
      "Passive (APIs)",
      "Active (bruteforce)",
      "Subdomain Permutation Engine",
      "Zone Transfer Check",
      "DNS Brute Force",
      "DNS History Tracking",
    ],
  },
  {
    key: "web_application_recon",
    title: "Web Application Recon",
    description: "Web stack and endpoint reconnaissance for target applications.",
    targetLabel: "Website URL/Domain",
    targetPlaceholder: "https://example.com",
    auxLabel: "Optional Endpoint Seed",
    auxPlaceholder: "/api,/admin,/v1",
    capabilities: [
      "Technology Detection (CMS, frameworks, libraries)",
      "WAF Detection",
      "HTTP Header Analysis",
      "Cookie Analysis",
      "Directory Bruteforce",
      "Endpoint Discovery (API paths)",
      "JavaScript Analysis (hidden endpoints)",
      "Website Screenshot Capture",
    ],
  },
  {
    key: "identity_social_osint",
    title: "Identity & Social OSINT",
    description: "Persona and social footprint intelligence gathering.",
    targetLabel: "Username",
    targetPlaceholder: "target_username",
    auxLabel: "Optional Email/Phone/Org",
    auxPlaceholder: "target@domain.com or +1-555-000-0000",
    capabilities: [
      "Username Search (multi-platform)",
      "Email -> Username correlation",
      "Phone Number OSINT",
      "Social Media Profile Scraping",
      "Employee Enumeration (LinkedIn-style)",
      "Persona Profiling",
    ],
  },
  {
    key: "email_intelligence",
    title: "Email Intelligence",
    description: "Email validation, header analysis, and infrastructure indicators.",
    targetLabel: "Email Address",
    targetPlaceholder: "person@company.com",
    auxLabel: "Raw Email Headers (optional)",
    auxPlaceholder: "Paste full header block for analysis",
    capabilities: [
      "Email Validation (SMTP check)",
      "Email Pattern Generation",
      "Email Header Analysis",
      "MX Record Analysis",
      "Disposable Email Detection",
    ],
  },
  {
    key: "credential_leak_intelligence",
    title: "Credential & Leak Intelligence",
    description: "Credential exposure and secret leakage monitoring.",
    targetLabel: "Leak Query/Email/Org Keyword",
    targetPlaceholder: "company.com OR user@company.com",
    auxLabel: "Optional Correlation Context",
    auxPlaceholder: "Known password fragment / campaign tag",
    capabilities: [
      "Breach Database Lookup",
      "Password Leak Correlation",
      "Combo List Builder",
      "GitHub Secret Scanner",
      "Paste Site Monitoring (Pastebin, etc.)",
    ],
  },
  {
    key: "cloud_osint",
    title: "Cloud OSINT",
    description: "Cloud asset discovery and misconfiguration reconnaissance.",
    targetLabel: "Domain/Org Keyword",
    targetPlaceholder: "example.com",
    auxLabel: "Optional Cloud Prefix Pattern",
    auxPlaceholder: "acme-prod,acme-dev",
    capabilities: [
      "AWS S3 Bucket Finder",
      "Azure Blob Exposure Check",
      "Google Cloud Storage Scan",
      "Cloud Asset Enumeration",
      "Public API Key Detection",
    ],
  },
  {
    key: "metadata_file_analysis",
    title: "Metadata & File Analysis",
    description: "Metadata extraction, hashing, and hidden artifact inspection.",
    targetLabel: "Optional File Context",
    targetPlaceholder: "Case note or source URL",
    auxLabel: "Optional Hash/Note",
    auxPlaceholder: "Known hash or collection notes",
    requiresFile: true,
    capabilities: [
      "Image EXIF Extraction (GPS, device)",
      "PDF Metadata",
      "DOCX Metadata",
      "File Hashing (MD5, SHA256)",
      "Steganography Indicators",
    ],
  },
  {
    key: "relationship_graph_analysis",
    title: "Relationship & Graph Analysis",
    description: "Entity correlation and timeline reconstruction.",
    targetLabel: "Primary Entity (domain/email/IP/username)",
    targetPlaceholder: "example.com",
    auxLabel: "Secondary Entity (optional)",
    auxPlaceholder: "user@company.com",
    capabilities: [
      "Entity Linking: Domain <-> IP <-> Email <-> Username",
      "Graph Visualization (nodes/edges)",
      "Timeline reconstruction",
    ],
  },
  {
    key: "automation_recon_pipelines",
    title: "Automation & Recon Pipelines",
    description: "Automated recon workflow execution and reporting.",
    targetLabel: "Pipeline Root Target",
    targetPlaceholder: "example.com",
    auxLabel: "Schedule/Workflow Notes",
    auxPlaceholder: "daily 03:00 UTC, medium depth",
    capabilities: [
      "Custom workflows: domain -> subdomains -> IPs -> ports -> CVEs",
      "Scheduled recon jobs",
      "Auto-report generation",
    ],
  },
  {
    key: "evasion_stealth",
    title: "Evasion & Stealth",
    description: "Stealth and anti-detection execution controls.",
    targetLabel: "Target or Campaign Name",
    targetPlaceholder: "example.com or campaign-01",
    auxLabel: "Proxy/User-Agent Configuration",
    auxPlaceholder: "proxy list, UA rotation policy",
    capabilities: [
      "Proxy configuration",
      "Proxy rotation",
      "TOR integration",
      "User-Agent randomization",
      "Rate limit bypass strategies",
    ],
  },
  {
    key: "offensive_intelligence_addons",
    title: "Offensive Intelligence Add-ons",
    description: "Vulnerability and exploit-oriented intelligence augmentation.",
    targetLabel: "Host/Domain/IP",
    targetPlaceholder: "example.com",
    auxLabel: "Optional Service Name",
    auxPlaceholder: "nginx, apache, openssh",
    capabilities: [
      "CVE Mapping (service -> vulnerability)",
      "Exploit DB linking",
      "Shodan/Censys integration",
      "Live host detection",
    ],
  },
];

const blueModules = [
  {
    key: "attack_surface_management",
    title: "Attack Surface Management (ASM)",
    description: "Monitor and map external exposed assets continuously.",
    targetLabel: "Organization Domain",
    targetPlaceholder: "company.com",
    auxLabel: "Optional Asset Context",
    auxPlaceholder: "Known IP blocks/API endpoints",
    capabilities: [
      "Asset inventory (domains, IPs, APIs)",
      "Subdomain monitoring (new assets)",
      "Service exposure detection",
      "Shadow IT detection",
      "External attack surface mapping",
    ],
  },
  {
    key: "threat_intelligence_ioc",
    title: "Threat Intelligence & IOC",
    description: "IOC ingestion, reputation checks, and threat scoring.",
    targetLabel: "IOC (IP/domain/hash)",
    targetPlaceholder: "1.1.1.1 or suspicious-domain.com",
    auxLabel: "Optional Threat Feed Tag",
    auxPlaceholder: "campaign-tag / malware-family",
    capabilities: [
      "IP/Domain reputation lookup",
      "IOC ingestion (IP, hash, domain)",
      "Malware domain detection",
      "Threat feed integration: VirusTotal, AbuseIPDB",
      "Threat scoring system",
    ],
  },
  {
    key: "phishing_brand_protection",
    title: "Phishing & Brand Protection",
    description: "Detect impersonation domains and social clones.",
    targetLabel: "Brand Name",
    targetPlaceholder: "acme",
    auxLabel: "Primary Domain (optional)",
    auxPlaceholder: "acme.com",
    capabilities: [
      "Typosquatting detection",
      "Homograph attack detection",
      "Fake domain monitoring",
      "Fake social media account detection",
      "SSL certificate monitoring",
    ],
  },
  {
    key: "data_leak_exposure_monitoring",
    title: "Data Leak & Exposure Monitoring",
    description: "Credential and data exposure detection across open sources.",
    targetLabel: "Emails/Keywords (comma/newline separated)",
    targetPlaceholder: "alice@company.com",
    auxLabel: "Optional Leak Scope",
    auxPlaceholder: "GitHub org, paste tags, dark-web keywords",
    capabilities: [
      "Credential leak detection (emails)",
      "GitHub leak monitoring",
      "Paste site monitoring",
      "Dark web monitoring (Tor sources)",
      "Public database exposure alerts",
    ],
  },
  {
    key: "employee_insider_risk_monitoring",
    title: "Employee & Insider Risk Monitoring",
    description: "Monitor employee exposure and potential insider risk signals.",
    targetLabel: "Employee Emails/Usernames",
    targetPlaceholder: "alice@company.com",
    auxLabel: "Optional Department/Team",
    auxPlaceholder: "finance, engineering, operations",
    capabilities: [
      "Employee email breach alerts",
      "Social footprint monitoring",
      "Privilege exposure tracking",
    ],
  },
  {
    key: "security_analytics_dashboard",
    title: "Security Analytics Dashboard",
    description: "Asset-level risk scoring and trend analytics.",
    targetLabel: "Optional Asset Filter",
    targetPlaceholder: "company.com",
    auxLabel: "Optional Time Window",
    auxPlaceholder: "last 7 days / last 30 days",
    capabilities: [
      "Risk score per asset",
      "Threat heatmap",
      "Attack timeline",
      "Trend analysis",
    ],
  },
  {
    key: "log_enrichment_siem_integration",
    title: "Log Enrichment & SIEM Integration",
    description: "Contextual enrichment for detections and SOC workflows.",
    targetLabel: "IP List (comma/newline separated)",
    targetPlaceholder: "8.8.8.8",
    auxLabel: "Export Target (optional)",
    auxPlaceholder: "Splunk / ELK / QRadar",
    capabilities: [
      "GeoIP enrichment",
      "ASN enrichment",
      "Threat score tagging",
      "Export to Splunk, ELK Stack, QRadar",
    ],
  },
  {
    key: "vulnerability_intelligence",
    title: "Vulnerability Intelligence",
    description: "Prioritize exposures via asset-to-CVE correlation.",
    targetLabel: "Asset Target",
    targetPlaceholder: "example.com",
    auxLabel: "Optional Patch Baseline",
    auxPlaceholder: "current patch cycle notes",
    capabilities: [
      "Asset -> CVE mapping",
      "Patch status tracking",
      "Exposure prioritization",
    ],
  },
  {
    key: "continuous_monitoring_alerts",
    title: "Continuous Monitoring & Alerts",
    description: "Continuous scanning and event-driven alerting workflows.",
    targetLabel: "Monitored Domain/Asset",
    targetPlaceholder: "company.com",
    auxLabel: "Notification Channel (optional)",
    auxPlaceholder: "email/slack/webhook",
    capabilities: [
      "Real-time alerts: New domain detected, New IP exposure, Credential leak",
      "Scheduled scans",
      "Notification system (Email, Slack, Webhook)",
    ],
  },
  {
    key: "threat_hunting_support",
    title: "Threat Hunting Support",
    description: "IOC-driven hunt workflows with historical correlation.",
    targetLabel: "Hunt Query (IOC/domain/email)",
    targetPlaceholder: "ioc:1.1.1.1 or domain:example.com",
    auxLabel: "Optional Hunt Hypothesis",
    auxPlaceholder: "describe threat-hunt objective",
    capabilities: [
      "Query engine for IOC search",
      "Historical data analysis",
      "Behavior correlation",
    ],
  },
  {
    key: "correlation_engine",
    title: "Correlation Engine",
    description: "Incident context building via cross-entity correlation.",
    targetLabel: "Correlation Seed (asset/user/alert)",
    targetPlaceholder: "asset:example.com",
    auxLabel: "Optional Incident Context",
    auxPlaceholder: "incident-id / case-notes",
    capabilities: [
      "Link: Alerts <-> assets <-> users",
      "Incident context building",
    ],
  },
];

const sharedCoreModules = [
  {
    title: "Core Utilities",
    capabilities: ["IP Lookup", "Domain Lookup", "DNS Lookup", "Email Lookup", "Username Search"],
  },
  {
    title: "Data Correlation Engine",
    capabilities: ["Cross-module intelligence linking", "Graph database support (Neo4j optional)"],
  },
  {
    title: "Data Storage",
    capabilities: ["Scan history", "Asset database", "Evidence storage"],
  },
  {
    title: "Reporting Engine",
    capabilities: ["PDF reports", "JSON export", "CSV export", "Executive summary + technical details"],
  },
  {
    title: "User Management",
    capabilities: ["Authentication (JWT/OAuth)", "Role-based access (Red team / Blue team / Admin)"],
  },
  {
    title: "API Integration Layer",
    capabilities: ["Shodan", "Censys", "VirusTotal", "Hunter.io", "HaveIBeenPwned"],
  },
  {
    title: "Configuration System",
    capabilities: ["API key manager", "Proxy settings", "Scan settings"],
  },
  {
    title: "UI/UX Modules",
    capabilities: ["Dashboard", "Universal search bar", "Graph visualization", "Scan progress tracker"],
  },
  {
    title: "Advanced Query Language",
    capabilities: ["domain:target.com", "email:gmail.com", "ip:8.8.8.8"],
  },
  {
    title: "AI/ML Enhancements (Optional)",
    capabilities: ["Predict usernames/emails", "Detect anomalies", "Auto-summarize findings"],
  },
];

function getRedModuleByKey(key) {
  return redModules.find((module) => module.key === key);
}

function getBlueModuleByKey(key) {
  return blueModules.find((module) => module.key === key);
}

module.exports = {
  redModules,
  blueModules,
  sharedCoreModules,
  getRedModuleByKey,
  getBlueModuleByKey,
};
